version: '2'
services:
    matchminercurate-app:
        image: matchminercurate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://matchminercurate-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=matchminerCurate
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    matchminercurate-mongodb:
        extends:
            file: mongodb.yml
            service: matchminercurate-mongodb
